#dist: trusty
language: java
jdk:
- openjdk11

addons:
  sonarcloud:
    organization: martina97
    token: 569a978c7b47fd065127944942a3fdb361cb04e3

     
install: 
  - mvn clean install -q -DskipTests=true 

script:
  - mvn clean verify sonar:sonar  -Dsonar.projectKey=martina97_bookkeeper
